<a href="https://colab.research.google.com/github/Muhammad-Awais-Awan/TensorFLow-MachineLearning/blob/main/Module2_basics_of_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

st=tf.Variable("this",tf.string)


In [10]:
rank1_tensor=tf.Variable(["test","1","wow"], tf.string)
rank2_tensor=tf.Variable([["test","1","wow"],["ee","ww","1"]], tf.string)

In [4]:
tf.rank(st)
tf.shape(st)

<tf.Tensor: shape=(0,), dtype=int32, numpy=array([], dtype=int32)>

In [12]:
tf.rank(rank1_tensor)
rank1_tensor.shape

TensorShape([3])

In [13]:
tf.rank(rank2_tensor)
rank2_tensor.shape

TensorShape([2, 3])

Reshaping and creating a new tensor with auto population

In [15]:
tensor1=tf.ones([1,2,3])
print(tensor1)#tf.ones() creates a shape [1,2,3] tensor full of ones
tensor2=tf.reshape(tensor1,[2,3,1])#reshape existing data to shape [2,3,1]
tensor3=tf.reshape(tensor2,[3,-1]) #-1 tells the tensor to calculate the size of the dimension in that place
                                   # this will reshape the tensor to [3,2]
                                   # the number of elements in reshape tensor must match the number in orignal

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [16]:
print (tensor1)
print (tensor2)
print (tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [1]:
with tf.Session() as sess:
  tensor.eval()

NameError: ignored

In [4]:
import tensorflow as tf
print(tf.version)
t=tf.zeros([5,5,5,5])

t=tf.reshape(t,[625])
print(t)


<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>
tf.Tensor(
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.